// Google Apps Script for Google Form → Supabase Integration
// Paste this into your Google Sheet's Apps Script editor (Extensions > Apps Script)

const SUPABASE_URL = "https://htxvrpgpvznzjhfdbcsj.supabase.co"
const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eHZycGdwdnpuempoZmRiY3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjEwMTksImV4cCI6MjA3NjY5NzAxOX0.y3GKRFbMH2rTkNdjVaMMZPUmk5SxvepR98byW_JscK4"

// Run debugFormStructure() first to see what's in each column
const COLUMN_MAPPING = {
  TIMESTAMP: 0, // Column A - Auto-generated by Google Forms
  NAME: 1, // Column B - Change this if your Name is in a different column
  EMAIL: 2, // Column C - Change this if your Email is in a different column
  PHONE: 3, // Column D - Change this if your Phone is in a different column
  COURSE: 4, // Column E - Change this if your Course is in a different column
  SCORE: 5, // Column F - Change this if your Score is in a different column
  EXAM_TYPE: 6, // Column G - Optional, change if needed
}

/**
 * Main function triggered when a form is submitted
 * This function extracts data from the Google Sheet and sends it to Supabase
 */
function onFormSubmit(e) {
  try {
    const sheet = SpreadsheetApp.getActiveSheet()
    const row = e.range.getRow()
    const data = sheet.getRange(row, 1, 1, sheet.getLastColumn()).getValues()[0]

    console.log("[v0] Raw form data:", data)
    console.log("[v0] Column mapping:", COLUMN_MAPPING)

    // Extract data using the column mapping
    const timestamp = data[COLUMN_MAPPING.TIMESTAMP] || new Date().toISOString()
    const name = String(data[COLUMN_MAPPING.NAME] || "").trim()
    const email = String(data[COLUMN_MAPPING.EMAIL] || "")
      .trim()
      .toLowerCase()
    const phone = String(data[COLUMN_MAPPING.PHONE] || "").trim()
    const course = String(data[COLUMN_MAPPING.COURSE] || "").trim()
    const score = data[COLUMN_MAPPING.SCORE] ? Number.parseFloat(data[COLUMN_MAPPING.SCORE]) : null
    const examType = String(data[COLUMN_MAPPING.EXAM_TYPE] || "Entrance").trim()

    console.log("[v0] Extracted data:", { name, email, phone, course, score, examType })

    // Validation
    if (!email && !phone) {
      console.log("[v0] Skipping: No email or phone provided")
      return
    }

    if (!name) {
      console.log("[v0] Warning: Name is empty")
    }

    if (score === null || isNaN(score)) {
      console.log("[v0] Warning: Score is null or invalid")
    }

    const result = score !== null && !isNaN(score) && score >= 50 ? "Passed" : "Failed"
    const submittedAt = new Date().toISOString()

    console.log("[v0] Processing submission:", { name, email, phone, course, score, examType, result })

    // Step 1: Insert into test_results table
    insertTestResult({
      name: name || null,
      email: email || null,
      phone: phone || null,
      course: course || null,
      exam: examType,
      score: score,
      submitted_at: submittedAt,
    })

    // Step 2: Update leads table with entrance score and status
    updateLeadWithScore(email, phone, score, result, examType)

    console.log("[v0] Submission processed successfully")
  } catch (error) {
    console.error("[v0] Error in onFormSubmit:", error.toString())
  }
}

/**
 * Insert test result into Supabase test_results table
 */
function insertTestResult(record) {
  const url = `${SUPABASE_URL}/rest/v1/test_results`

  const payload = {
    name: record.name,
    email: record.email,
    phone: record.phone,
    course: record.course,
    exam: record.exam,
    score: record.score !== null ? record.score : null,
    submitted_at: record.submitted_at,
  }

  console.log("[v0] Inserting test result:", payload)

  const options = {
    method: "POST",
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      "Content-Type": "application/json",
      Prefer: "return=representation",
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
  }

  try {
    const response = UrlFetchApp.fetch(url, options)
    const code = response.getResponseCode()
    const responseText = response.getContentText()

    console.log(`[v0] Test result insert response code: ${code}`)
    console.log(`[v0] Response: ${responseText}`)

    if (code === 201 || code === 204) {
      console.log("[v0] Test result inserted successfully")
      return true
    } else {
      console.error("[v0] Insert failed with code:", code)
      console.error("[v0] Response:", responseText)
      return false
    }
  } catch (error) {
    console.error("[v0] Error inserting test result:", error.toString())
    return false
  }
}

/**
 * Update lead with entrance score and status
 */
function updateLeadWithScore(email, phone, score, result, examType) {
  let filter = ""
  if (email) {
    filter = `email=eq.${encodeURIComponent(email)}`
  } else if (phone) {
    filter = `phone=eq.${encodeURIComponent(phone)}`
  }

  if (!filter) {
    console.log("[v0] No email or phone to filter leads")
    return false
  }

  const url = `${SUPABASE_URL}/rest/v1/leads?${filter}`

  let newStatus = "Pending Final Exam"
  if (result === "Failed") {
    newStatus = "Rejected"
  } else if (examType.toLowerCase().includes("final")) {
    newStatus = "Completed"
  }

  const payload = {
    entrance_score: score !== null ? score : null,
    final_score: result === "Passed" && examType.toLowerCase().includes("final") ? score : null,
    status: newStatus,
    updated_at: new Date().toISOString(),
  }

  console.log("[v0] Updating lead with:", payload)

  const options = {
    method: "PATCH",
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
      "Content-Type": "application/json",
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true,
  }

  try {
    const response = UrlFetchApp.fetch(url, options)
    const code = response.getResponseCode()
    const responseText = response.getContentText()

    console.log(`[v0] Lead update response code: ${code}`)
    console.log(`[v0] Response: ${responseText}`)

    if (code === 200 || code === 204) {
      console.log("[v0] Lead updated successfully with score:", score, "and status:", newStatus)
      return true
    } else {
      console.error("[v0] Update failed with code:", code)
      console.error("[v0] Response:", responseText)
      return false
    }
  } catch (error) {
    console.error("[v0] Error updating lead:", error.toString())
    return false
  }
}

/**
 * Debug function - shows the column structure of your form
 * Run this to see what data is in each column
 * Steps:
 * 1. Go to your Google Sheet
 * 2. Click Extensions > Apps Script
 * 3. Click the Run button next to debugFormStructure
 * 4. Check the Execution log to see the output
 */
function debugFormStructure() {
  const sheet = SpreadsheetApp.getActiveSheet()
  const lastRow = sheet.getLastRow()

  if (lastRow < 2) {
    console.log("[v0] No data rows found")
    return
  }

  // Get the last row of data
  const data = sheet.getRange(lastRow, 1, 1, sheet.getLastColumn()).getValues()[0]

  console.log("[v0] === Form Structure Debug ===")
  console.log("[v0] Total columns:", data.length)
  console.log("[v0] Last row number:", lastRow)
  console.log("[v0] ")

  for (let i = 0; i < data.length; i++) {
    const columnLetter = String.fromCharCode(65 + i)
    console.log(`[v0] Column ${i} (${columnLetter}): "${data[i]}"`)
  }

  console.log("[v0] ")
  console.log("[v0] === Update COLUMN_MAPPING at the top of the script ===")
  console.log("[v0] If your columns are in a different order, update the COLUMN_MAPPING object")
}

/**
 * Test function - run this to verify setup
 * Go to Extensions > Apps Script > Run > testIntegration
 */
function testIntegration() {
  console.log("[v0] Starting integration test...")

  const testEmail = "test@example.com"
  const testPhone = "9999999999"

  const testRecord = {
    name: "Test User",
    email: testEmail,
    phone: testPhone,
    course: "Fullstack",
    exam: "Entrance",
    score: 75,
    submitted_at: new Date().toISOString(),
  }

  console.log("[v0] Testing with record:", testRecord)

  // Test 1: Insert test result
  const insertSuccess = insertTestResult(testRecord)
  console.log("[v0] Insert test result:", insertSuccess ? "SUCCESS" : "FAILED")

  // Test 2: Update lead with score
  const updateSuccess = updateLeadWithScore(testEmail, testPhone, 75, "Passed", "Entrance")
  console.log("[v0] Update lead with score:", updateSuccess ? "SUCCESS" : "FAILED")

  console.log("[v0] Integration test complete - check Supabase for records")
}
