export { getSupabaseClient } from "./client"
export * from "./types"
export * from "./leads"
export * from "./courses"
export * from "./batches"
export * from "./teachers"
export * from "./students"
export * from "./attendance"
export * from "./test-results"
export * from "./exams"
